#!/bin/sh


# Exit on first error
set -e


# Unit-tests the libraries.
# (Static checks took already place during commits)
# 
# Don't run if there are just changes to the documentation
# 
if git diff --stat --cached origin/master | grep -E "(\.pm|\.t)"
then
	prove
fi




