#!/bin/sh

if git status --porcelain ./lib/Goodscrapes.pm | grep "^M"
then
	echo "Generating documentation: Goodscrapes.pod"
	podselect ./lib/Goodscrapes.pm > ./lib/Goodscrapes.pod \
		&& git add ./lib/Goodscrapes.pod
fi


