#!/usr/bin/env bash


# Exit on first error
set -e


# Static code checks:
for f in `git ls-files --modified *.pl`
do
	perl -c "${f}"
done


# Generate documentation:
if git ls-files --modified ./lib/Goodscrapes.pm
then
	echo "Generating documentation: Goodscrapes.pod"
	podselect ./lib/Goodscrapes.pm > ./lib/Goodscrapes.pod \
		&& git add ./lib/Goodscrapes.pod
fi


