#!/usr/bin/env bash

GOODUSERNUMBER="18418712"
GOODUSERNAME="andre"

#GOODUSERNUMBER="52355788"
#GOODUSERNAME="anne";

MINFAVORERS="4"
OUTXMLPATH="${GOODUSERNUMBER}-${GOODUSERNAME}.xml"
OUTHTMLPATH="${GOODUSERNUMBER}-${GOODUSERNAME}.html"
LOGPATH="${GOODUSERNUMBER}-${GOODUSERNAME}.log"


(
	./friendrated.pl "${GOODUSERNUMBER}" "${OUTXMLPATH}" "${MINFAVORERS}" \
		&& xsltproc friendrated.xsl "${OUTXMLPATH}" > "${OUTHTMLPATH}"
	
) | tee "$LOGPATH"

